# Generated by Django 4.2.3 on 2023-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopes',
            old_name='artile_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.Scopes', to='articles.tag'),
        ),
    ]
