# Generated by Django 4.2.4 on 2023-08-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='sensor_name',
            new_name='sensor_id',
        ),
    ]
