# Generated by Django 4.2.4 on 2023-08-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurements_sensor_id_measurements_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor', verbose_name='Датчик'),
        ),
    ]
